// <auto-generated />
using System;
using BulgarianMountainTrailsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulgarianMountainTrailsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250827183223_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulgarianMountainTrailsAPI.Data.Models.MountainHut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Altitude")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Mountain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Huts");
                });

            modelBuilder.Entity("BulgarianMountainTrailsAPI.Data.Models.Trail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<double>("DurationHours")
                        .HasColumnType("float");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LengthKm")
                        .HasColumnType("float");

                    b.Property<string>("Mountain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trails");
                });

            modelBuilder.Entity("BulgarianMountainTrailsAPI.Data.Models.TrailHut", b =>
                {
                    b.Property<Guid>("TrailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TrailId", "HutId");

                    b.HasIndex("HutId");

                    b.ToTable("TrailHuts");
                });

            modelBuilder.Entity("BulgarianMountainTrailsAPI.Data.Models.TrailHut", b =>
                {
                    b.HasOne("BulgarianMountainTrailsAPI.Data.Models.MountainHut", "Hut")
                        .WithMany("TrailHuts")
                        .HasForeignKey("HutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BulgarianMountainTrailsAPI.Data.Models.Trail", "Trail")
                        .WithMany("TrailHuts")
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hut");

                    b.Navigation("Trail");
                });

            modelBuilder.Entity("BulgarianMountainTrailsAPI.Data.Models.MountainHut", b =>
                {
                    b.Navigation("TrailHuts");
                });

            modelBuilder.Entity("BulgarianMountainTrailsAPI.Data.Models.Trail", b =>
                {
                    b.Navigation("TrailHuts");
                });
#pragma warning restore 612, 618
        }
    }
}
